config/routes.rb
ColorManiac::Application.routes.draw do
  resources :paintings do
    member do
      get 'download'
    end
  end

  resources :galleries do
    member do
      get 'paintings'
      get 'thumbnail'
    end
  end

  root :to => "galleries#index"

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  has_many :paintings

  validates_presence_of :name

  def product_id
    "%02d" % id
  end

  def serializable_hash(options = nil)
	  super(:only => [], :methods => [:product_id])
	end
end

app/models/painting.rb
class Painting < ActiveRecord::Base
  belongs_to :gallery

  has_attached_file :picture,
                    :styles => { :normal => ["832x768>", :png], :thumb => ["130x130>", :png] },
                    :storage => :s3,
                    :path => ":attachment/:id/:style.png",
                    :s3_credentials => File.join(Rails.root, 'config', 's3.yml')

  validates_attachment_presence :picture

  validates_presence_of :picture, :title, :author, :gallery_id

  def serializable_hash(options = nil)
	  super(:only => [:id, :title, :author])
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected

  def authenticate
    authenticate_or_request_with_http_basic("ColorManiac") do |username, password|
      username == "administrator" && password == "password"
    end
  end
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :paintings, :thumbnail]

  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html
      format.json do
        render :json => @galleries
      end
    end
  end

  def show
    @gallery = Gallery.find(params[:id])
    @painting = @gallery.paintings.build

    respond_to do |format|
      format.html
    end
  end

  def new
    @gallery = Gallery.new

    respond_to do |format|
      format.html
    end
  end

  def edit
    @gallery = Gallery.find(params[:id])
  end

  def create
    @gallery = Gallery.new(params[:gallery])

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to(@gallery, :notice => 'Gallery was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end

  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to(@gallery, :notice => 'Gallery was successfully updated.') }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to(galleries_url) }
    end
  end

  def paintings
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      format.html
      format.json do
        render :json => @gallery.paintings
      end
    end
  end

  def thumbnail
    @gallery = Gallery.find(params[:id])

    redirect_to @gallery.paintings.first.picture.url('thumb')
  end
end

app/controllers/paintings_controller.rb
class PaintingsController < ApplicationController
  before_filter :authenticate, :except => [:show, :download]

  def download
    redirect_to Painting.find(params[:id]).picture.url(params[:style])
  end

  def show
    @painting = Painting.find(params[:id])

    respond_to do |format|
      format.html
    end
  end

  def edit
    @painting = Painting.find(params[:id])
  end
    
  def create
    @painting = Painting.create(params[:painting])
    @gallery = @painting.gallery

    respond_to do |format|
      if @painting.save
        format.html { redirect_to(@gallery, :notice => 'Painting was successfully created.') }
      else
        format.html { render 'galleries/show' }
      end
    end
  end

  def update
    @painting = Painting.find(params[:id])
    @gallery = @painting.gallery
        
    respond_to do |format|
      if @painting.update_attributes(params[:painting])
        format.html { redirect_to(@gallery, :notice => 'Painting was successfully updated.') }
      else
        format.html { render 'galleries/show' }
      end
    end
  end
    
  def destroy
    @painting = Painting.find(params[:id])

    respond_to do |format|
      if @painting.destroy
        format.html { redirect_to(@painting.gallery) }
      else
        format.html { render :show }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/paintings_helper.rb
module PaintingsHelper
end

app/views/galleries/_form.html.erb
<%= form_for(@gallery) do |f| %>
  <% if @gallery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gallery.errors.count, "error") %> prohibited this gallery from being saved:</h2>

      <ul>
      <% @gallery.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/galleries/edit.html.erb
<h1>Editing gallery</h1>

<%= render 'form' %>

<%= link_to 'Show', @gallery %> |
<%= link_to 'Back', galleries_path %>

app/views/galleries/index.html.erb
<h1>Listing galleries</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @galleries.each do |gallery| %>
  <tr>
    <td><%= gallery.name %></td>
    <td><%= link_to 'Show', gallery %></td>
    <td><%= link_to 'Edit', edit_gallery_path(gallery) %></td>
    <td><%= link_to 'Destroy', gallery, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Gallery', new_gallery_path %>

app/views/galleries/new.html.erb
<h1>New gallery</h1>

<%= render 'form' %>

<%= link_to 'Back', galleries_path %>

app/views/galleries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @gallery.name %><br />
  <b>Product ID:</b>
  <%= @gallery.product_id %>
</p>

<ul id="paintings">
<% @gallery.paintings.each do |painting| %>
  <% if !painting.new_record? %>
  <li><%= link_to image_tag(painting.picture.url(:thumb)), painting_path(painting) %></li>
  <% end %>
<% end %>
</ul>

<%= form_for @painting, :html => { :multipart => true }  do |f| %>
  <%= f.hidden_field :gallery_id %>

  <%= f.label :author %>:
  <%= f.text_field :author %><br />

  <%= f.label :title %>:
  <%= f.text_field :title %><br />

  <%= f.label :picture %>:
  <%= f.file_field :picture %><br />

  <%= f.submit %>
<% end %>

<%= link_to 'Edit', edit_gallery_path(@gallery) %> |
<%= link_to 'Back', galleries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ColorManiac</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/paintings/_form.html.erb
<%= form_for(@painting) do |f| %>
  <% if @painting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@painting.errors.count, "error") %> prohibited this painting from being saved:</h2>

      <ul>
      <% @painting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paintings/edit.html.erb
<h1>Editing painting</h1>

<%= render 'form' %>

<%= link_to 'Show', @painting %> |
<%= link_to 'Back', gallery_path(@painting.gallery) %>

app/views/paintings/show.html.erb
<p>
  <b>Title:</b>
  <%= @painting.title %><br />
  <b>Author:</b>
  <%= @painting.author %>
</p>

<p><%= image_tag @painting.picture.url(:normal) %></p>

<%= link_to 'Edit', edit_painting_path(@painting) %> |
<%= link_to 'Destroy', painting_path(@painting), :confirm => 'Are you sure?', :method => :delete %> |
<%= link_to 'Back', gallery_path(@painting.gallery) %>